repos:
  - repo: local
    hooks:
      - id: Unit Tests
        name: Unit Tests
        language: system
        description: runs all unittests in /Tests/unit
        pass_filenames: false
        verbose: true
        entry: python -m unittest discover -s Tests/unit
