repos:
  - repo: https://github.com/psf/black
    rev: "23.1.0"
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: Tests
        name: Tests
        language: system
        description: runs all unittests in /Tests/
        pass_filenames: false
        verbose: true
        entry: python -m unittest discover -s Tests
